In [1]:
import pandas as pd

In [2]:
df_name = pd.read_csv('Resources/Body_Bark_Customer_list_bill_address.csv')

In [4]:
type(df_name["zip"])

pandas.core.series.Series

In [5]:
df_name[['zip_code','extra']] = df_name.zip.str.split(pat='-', expand=True)

In [7]:
#for i in range(len([df_name.zip])):
df_name['zip_code']=df_name['zip_code'].apply(lambda x: '{0:0>5}'.format(x))

In [9]:
type(df_name['zip_code'][0])

str

In [10]:
df_filtered = df_name.drop(['zip', 'extra'], axis=1)  #axis changes from row to column

In [11]:
boutique_customers_df = df_filtered.rename(columns={"zip_code": "zip"})

In [13]:
boutique_customers_df.reset_index(inplace=True)

In [14]:
boutique_customers_df = boutique_customers_df.rename(columns={"index": "boutique_id"})

In [17]:
column_names = ['boutique_id', 'boutique_name', 'street_address', 'city', 'state', 'zip']
boutique_customers__columnorder_df = boutique_customers_df.reindex(columns=column_names)

In [18]:
boutique_customers__columnorder_df.head(30)

,boutique_id,boutique_name,street_address,city,state,zip
0,0,A City Obsession,500 12th St. #128,Oakland,CA,94607
1,1,A Line Boutique,2000 S Acoma St.,Denver,CO,80223
2,2,Abigail Inc.,1216 Porta Ballena,Alameda,CA,94501
3,3,Abode,2416 Magowan Dr.,Santa Rosa,CA,95405
4,4,Adobe East,303 Southeast 17th Street #106,Ocala,FL,34471
5,5,Alene Women's Boutique-Closed,502 N. Pine Island Rd.,Plantation,FL,33324
6,6,Alice Becker,806 Grant Ave.,Novato,CA,94945
7,7,"Allied Feeds, Inc.",1551 N. Esplanade,Cuero,TX,77954
8,8,American Clothing Gallery,100 N 8th St.,Boise,ID,83702
9,9,Ann Marie - CLOSED,Ann Marie\n4000 East Madison,Seattle,WA,98112
10,10,Aquamarine,114 2nd Street,Lewes,DE,19958
11,11,Aromatherapy Closed,Aromatherapy\n326 Main St.,Huntington,NY,11743
12,12,Artemisia,117 Bent St,Taos,NM,87571
13,13,Artwear,185 Massachusetts Ave.,Arlington,MA,02474
14,14,At Ease,6325 Falls of Neuse Road,Raleigh,NC,27615
15,15,B. Real Women's Apparel,PO Box 5096,Carmel,CA,93921
16,16,Barbara and Company,1067 S. Gaylord St.,Denver,CO,80209
17,17,Barbara Eclectic CLOSED,Barbara Eclectic\n594 Valley Rd.,Upper Montclair,NJ,07043
18,18,Basiques,14210 Overbrook Lane,Houston,TX,77077
19,19,BB's Apparel and Boots,2340 East Murray Holladay Rd,Holladay,UT,84117
20,20,Beautiful,120 W. Main St.,Grass Valley,CA,95945
21,21,Bellagio Art to Wear,Historic Biltmore Village\n5 Biltmore Plaza,Asheville,NC,28803
22,22,Bellanova,222 96th Street,Stone Harbor,NJ,08247
23,23,Betsy Prince,608 Brookwood Village,Birmingham,AL,35209
24,24,Biba- In Collections,Biba\n40 Hill Street,Southhampton,NY,11968
25,25,Bill Paul Limited,112 W. Wisconsin Ave.,Neenah,WI,54956
26,26,Birdies Lingerie,116 W 18th St,Kansas City,MO,64108
27,27,BK & Company,983 Farmington Ave.,West Hartford,CT,06107
28,28,Bleu Company,807 William Hilton Pkwy,Hilton Head Island,SC,29928
29,29,Body of Santa Fe,"333 W Cordova Road, Ste 200",Santa Fe,NM,87505

In [19]:
boutique_customers__columnorder_df.to_csv('output/Boutiques.csv', index = False)